#!/usr/bin/env python3
"""Generate the Eisel-Lemire power-of-ten table.

Writes ``include/strata/util/eisel_lemire_table.inc``: for every decimal
exponent q in [-348, 347], the normalized 128 most significant bits of 10^q —
truncated for q >= 0, rounded up for q < 0 (the reciprocal direction), top bit
always set. These are the constants the Eisel-Lemire algorithm multiplies a
parsed mantissa against (``fast_parse.hpp``); the range matches Go's
strconv table, whose algorithm structure the C++ port follows.

Exact big-integer arithmetic throughout — nothing here depends on floating
point. Deterministic output: regenerating must produce a byte-identical file.
"""

from __future__ import annotations

from pathlib import Path

MIN_EXP10 = -348
MAX_EXP10 = 347

PROJECT_ROOT = Path(__file__).resolve().parents[1]
TARGET = PROJECT_ROOT / "include" / "strata" / "util" / "eisel_lemire_table.inc"


def mantissa_128(exp10: int) -> int:
    """The normalized 128-bit mantissa of 10**exp10, top bit set."""
    if exp10 >= 0:
        value = 10**exp10
        bits = value.bit_length()
        # Truncate (or pad) to exactly the 128 most significant bits.
        mantissa = value >> (bits - 128) if bits > 128 else value << (128 - bits)
    else:
        # Reciprocal: ceil(2^(bits+127) / 10^-exp10). The denominator is never
        # a power of two (it carries a factor of 5), so floor + 1 is ceil and
        # the quotient of a numerator in [2^(bits+126), 2^(bits+127)) lands in
        # [2^127, 2^128) after the round-up.
        denominator = 10**-exp10
        bits = denominator.bit_length()
        mantissa = (1 << (bits + 127)) // denominator + 1
    assert (1 << 127) <= mantissa < (1 << 128), exp10
    return mantissa


def main() -> int:
    lines = [
        "// Generated by scripts/gen_eisel_lemire_table.py -- do not edit by hand.",
        "// kEiselLemirePow10[q - kEiselLemireMinExp10] holds {hi, lo}: the",
        "// normalized 128 most significant bits of 10^q, truncated for q >= 0 and",
        "// rounded up for q < 0, top bit always set. Range: q in [-348, 347].",
        f"inline constexpr uint64_t kEiselLemirePow10[{MAX_EXP10 - MIN_EXP10 + 1}][2] = {{",
    ]
    for exp10 in range(MIN_EXP10, MAX_EXP10 + 1):
        mantissa = mantissa_128(exp10)
        hi, lo = mantissa >> 64, mantissa & ((1 << 64) - 1)
        lines.append(f"    {{0x{hi:016X}, 0x{lo:016X}}}, // 1e{exp10}")
    lines.append("};")
    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {TARGET} ({MAX_EXP10 - MIN_EXP10 + 1} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
